### ISSUE TITLE
Some subjects fall too quickly

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#101]
Your mom (luv her) has a very high proportion of false negatives simply because she falls and recovers too quickly.![image](https://github.com/VisualPT/visualPT/assets/124405841/64cca13a-9bfb-4935-9505-c671836b1281)

![image](https://github.com/VisualPT/visualPT/assets/124405841/f7d5b7f1-3a48-4ac0-893b-653c87fae8d2)

![image](https://github.com/VisualPT/visualPT/assets/124405841/b6c21e40-732f-4083-a023-eea024af5c1d)

![image](https://github.com/VisualPT/visualPT/assets/124405841/21bc40b2-945e-4ab7-a3ea-e6a58633eb61)

@charlieforward9

**Comment by Timothyrichpt** [comment]
I don't know the solution for this, perhaps instructions to the subject?

**Comment by charlieforward9** [comment]
Use the `Toggle Label` button to switch the classification if it is not correct.

### My Instructions:  

> Stand still with your arms crossed for about 3 seconds. Then, simulate a fall and recovery for about 3 seconds. Repeat this loop 5 times.

As the data collector, you can expect to press the button about every 3 seconds.

 I updated #53 to include this. We can continue the data collection discussion there, as it is not a technical Issue related to the source code.

**Comment by Timothyrichpt** [comment]
Yep, agreed. I think that might be the solution; have a standardized set of instructions for all test subjects so that we can anticipate when the fall will occur.


Love Your Life!

Tim


Want to schedule a call with Tim?

Put yourself on Tim's calendar here:

Calendly.com/Grow-With-Tim<https://calendly.com/grow-with-tim>


Tim Richardson, PT

Franchise Regional Consultant

Central Region, USA


FYZICAL LLC

World Headquarters

Bayou Professional Center

1751 Mound Street, <x-apple-data-detectors://2/1> Suite 101<x-apple-data-detectors://2/1>

Sarasota, Florida  34236<x-apple-data-detectors://2/1>


Mobile:  1.941.623.6109<tel:1.941.623.6109>


"Spelled Different Because We Are Different"


FYZICAL is Changing Lives and Changing Healthcare for Millions of Americans by Helping People Live Independently in Their Homes Without Fear of Falling.

On Sep 5, 2023, at 9:24 PM, Charles Richardson ***@***.***> wrote:

﻿

Use the Toggle Label button to switch the classification if it is not correct.

My Instructions:

Stand still with your arms crossed for about 3 seconds. Then, simulate a fall and recovery for about 3 seconds. Repeat this loop 5 times.

As the data collector, you can expect to press the button about every 3 seconds.

I updated #53<https://github.com/VisualPT/visualPT/discussions/53> to include this. We can continue the data collection discussion there, as it is not a technical Issue related to the source code.

**Comment by charlieforward9** [comment]
The task of this issue will be creating a more detailed "Assessment/Condition Description" page for the user.

I changed the name to reflect that.

**Comment by charlieforward9** [comment]
Actually, This is a subset of #27, you can subscribe to that for updates on non-critical UI enhancements. Closing this issue.
