### ISSUE TITLE
[Analysis] Compute Condition Ratios

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#105]
@charlieforward9 

Here is the PDF output from the competition; second graph is ratios.

- SOM test is C2/C1

- VIS test is C4/C1 

- VEST test is C5/C1 

- PREF test is C3 +C6 / C2+ C5 

If ratio < 1 => their system is disfunctional

https://www.dropbox.com/scl/fi/kqa7m1f2p3wv6emmog75n/Assessment-Report-5.pdf?rlkey=0h1u100dx5kk6f4yw7gvd7hgu&dl=0

**Comment by charlieforward9** [comment]
@Timothyrichpt the dropbox link is dead. If you find it and want it in the PDF, send it soon.

I will finish this within 2 hours.

**Comment by Timothyrichpt** [comment]
This is the only Dropbox link that I’m aware of; what were you referring to?
