### ISSUE TITLE
[Assessment/Collection] Method for CTSIB condition 3 and 6

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#107]
The patient may need VR goggles to view the Optokinetic flow during the performance of Condition #3 (new) and Condition #6 (new) - see video of Optokinetic Flow.
[https://vimeo.com/867727025?share=copy](url)
@charlieforward9

**Comment by Timothyrichpt** [comment]
I couldn't figure out how to set this up as a project

**Comment by charlieforward9** [comment]
This should not change the assessment procedure, we may just need to add a reminder to the screen before the recording to prompt the therapist to prepare the VR headset.

**Comment by charlieforward9** [comment]
@Timothyrichpt Conditions 3 and 6 are in the new version of the app (1.0.3)

**Comment by Timothyrichpt** [comment]
Do you see the optimal kinetic flow video being supplied by a second mobile device?

**Comment by charlieforward9** [comment]
@Timothyrichpt If they already have a VR headset, then Yes.

If not, I can spend some time building a VR Video screen for these conditions such that we can place the device within something like a [Google Cardboard](https://vr.google.com/cardboard/) and use the accelerometer in the device to measure these conditions. 

This would be somewhat of a heavy lift on my end though, and it would technically remove the need for the classification model for these two conditions.

**Comment by charlieforward9** [comment]
@Timothyrichpt I believe it would be most reasonable to stay consistent with how we "collect" data to be focused on the visual capture (video) and not the motion capture (accelerometer) with respect to the patient. 

Assuming we will continue to capture the subject visually, the action item from this issue would be to add a reminder guideline to prepare the VR device for the conditions before beginning data collection with the VisualPT app which is included as a task in #27 and #132

**Comment by charlieforward9** [comment]
Closed by https://github.com/VisualPT/visualPT/pull/171
