### ISSUE TITLE
The model struggles to detect forward sway

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#108]
Forward trunk flexion or forward bending does not show up well in the model.

The camera takes a 2-D image of a 3-D space, but doesn't do a good job of capturing forward bending as you can see in this example.

![image](https://github.com/VisualPT/visualPT/assets/124405841/360d5413-9a0d-4d24-8cbf-2bbf4012739f)

**Comment by charlieforward9** [comment]
Im unsure of what the action item is here. This needs to be labeled as sway and the classification model should learn based on the wireframe. 

There is a z-index that represent the forward/backward displacement of the hips. It is sent to @DrBubbles42 to train the model. Is it being used in the training?

**Comment by DrBubbles42** [comment]
So far th z axis is being used but I'm concerned about how accurate it is due to the 2d nature of the images. I can test with and without it and see if there's any difference.

**Comment by charlieforward9** [comment]
Closing this as there is nothing to do about it in the VisualPT repo
