### ISSUE TITLE
[Collection/Video] Horizontal and Subject Sway overlays

### ISSUE THREAD

**Issue by charlieforward9** [charlieforward9/visualPT#110]
> Overlay a fixed box on the camera viewport to indicate where the patient should be during the recording.

Rationale Detailed Here: https://github.com/VisualPT/docs/discussions/11#discussioncomment-7129673

- [x] Bounding Box with 12-15 degree tilt
- [x] Horizontal/vertical line

**Comment by Timothyrichpt** [comment]
Yep, I think this is what we need to get us to a mobile app MVP for validation in New Orleans.

The two camera solution or the 3-D camera solution would be a significant upgrade in both software and hardware that might be an interesting discussion for phase 2, down the road.

**Comment by charlieforward9** [comment]
@Timothyrichpt @DrBubbles42 I used trig for the first time outside of an academic setting! Heres the box, with a 12-degree angle on the sides.

![IMG_17D28042A78D-1](https://github.com/VisualPT/visualPT/assets/62311337/e3a9d755-459a-46df-9988-bbe4023947d4)

**Comment by charlieforward9** [comment]
Overlay a horizontal line that estimates the sway angle of the subject: computed from the line of best fit on a vertical axis of all the landmark points.

**Comment by Timothyrichpt** [comment]
Also, a vertical line bisecting the center of mass of the subject.

Can you do that?

**Comment by charlieforward9** [comment]
@Timothyrichpt sure, is this supposed to be a static line in the middle of the screen or a line that follows the center of the landmarks on a horizontal axis similar to the vertical one?

**Comment by charlieforward9** [comment]
https://github.com/VisualPT/visualPT/assets/62311337/abdecb61-6e8b-40af-9abe-2f2bf386d84c

Here is a demo of how the sway overlay looks now. 

Degrees will be handled/presented later, when gyro is hooked up.
