### ISSUE TITLE
[Analysis] add sway degree estimate to PDF, reformat

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#111]
- [x] Add max sway for each condition
- [x] Look at chart solutions comparable to below screenshots 
- [x] Calculate stability ratio to display Stages of Severity of Sway?

![image](https://github.com/VisualPT/visualPT/assets/124405841/2c0c881d-75c5-4e60-a2bd-e5538bec3f26)

**Comment by Timothyrichpt** [comment]
What about displaying vertical bars with the seconds compared to the total (30 seconds) for each condition? Similar to the existing SOT score as measured by the $5000 BodiTrack system?![image](https://github.com/VisualPT/visualPT/assets/124405841/876b3bb2-9aa9-44ea-9c11-8154189dca72)

**Comment by charlieforward9** [comment]
@Timothyrichpt 

Any chance you. have access to the equations for:
- [x] Equilibrium Score
- [x] Sensory Mismatch

**Comment by charlieforward9** [comment]
@Timothyrichpt Take a look at this and let me know if youd still like the charts to be added.

![image](https://github.com/VisualPT/visualPT/assets/62311337/47d368fa-982b-4c44-b80b-c8e0f2f5229b)

I may be able to add them on another page. Just show this to some industry members and give me THEIR feedback as well as yours.

**Comment by Timothyrichpt** [comment]
@charlieforward9 

Step one would be Stages of Severity of Sway - 4 stages is fine like in the image:
- Severe sway 
- Moderate sway, 
- mild sway, 
- no sway
 
![image](https://github.com/VisualPT/visualPT/assets/124405841/3872b1f5-e96e-4629-9b29-3abd9824c57c)

**Comment by charlieforward9** [comment]
@Timothyrichpt Im gonna need a hand translating this into an action item. How are they calculating these percentages below the black arrow? Is this correct?

$$\frac{\text{Static time}}{\text{Total time}} = \text{Stability Ratio}$$

**Comment by charlieforward9** [comment]
Equilibrium Score: https://vimeo.com/953222283/8331648c5b

**Comment by charlieforward9** [comment]
Starting to figure out calculating for equlibrium score by reviewing some linear algebra: https://math.stackexchange.com/q/1611308/1317011

**Comment by charlieforward9** [comment]
![Image](https://github.com/user-attachments/assets/6348aacb-7d5b-499a-af96-ee14e2a16824)

02f0bae2c9f9d23633d9aa1f2ec9dce3dcb2bb88 adds stages of severity, stability ratio and sensory mismatch into the CTSIB PDF.
