### ISSUE TITLE
Weird guy showing up in the validation

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#134]
Every time I close the app and reopen it about 20 images of this guy show up in front of the actual test images.

I have invalidated these images three times now, but he keeps popping up every time I close the app

![image](https://github.com/VisualPT/balance_model/assets/124405841/7adf6da6-2777-40fc-8b9f-d7cf3d230069)

![image](https://github.com/VisualPT/balance_model/assets/124405841/f9e12244-60e8-451c-8b10-8c86c16a71a6)

![image](https://github.com/VisualPT/balance_model/assets/124405841/2cfdc6e8-c403-48ef-a415-35a373834503)

**Comment by charlieforward9** [comment]
Are the same images showing up?

**Comment by Timothyrichpt** [comment]
Yep, third time now. I walk away from the app for a few minutes, and I go start it back up to validate the images and there he is again.

**Comment by Timothyrichpt** [comment]
I got down to 3400 images and now it’s telling me I’m back at 3117 images again.

And, this guy shows up again. All I did was back out of the validation screen to the app homepage, and then click ‘validate’ again.

**Comment by Timothyrichpt** [comment]
![image](https://github.com/VisualPT/balance_model/assets/124405841/504ec224-f757-4dfd-ac17-07a3a6751df9)

**Comment by Timothyrichpt** [comment]
It says I'm back at 3717 images to validate
