### ISSUE TITLE
Test glitch

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#138]
@charlieforward9 
App resets to Home Screen

I completed one full test of your mom with no trouble but when she took condition #1 with me, you can see the behavior in this video:

https://github.com/VisualPT/visualPT/assets/124405841/52837dae-adcc-46a8-a0a1-322091ce2089

**Comment by charlieforward9** [comment]
What is the app version?

**Comment by Timothyrichpt** [comment]
I think we figured it out; we clicked “collect data”. We should’ve clicked “CTSIB”.

**Comment by charlieforward9** [comment]
Ok, I will be removing this ambiguous "Collect Data" control soon as the assessments will have custom storage buckets and we will be collecting more data on the subject, etc.

Working on this now.
