### ISSUE TITLE
Invalid images

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#151]
I think this an invalid image.
Please be aware that if you use the app and create invalid images, I have to spend time invalidating those images. 
Please only use test subjects. 
@charlieforward9 

![image](https://github.com/VisualPT/visualPT/assets/124405841/370bbc6b-f4ad-4048-af57-26ddff60ea6e)

![image](https://github.com/VisualPT/visualPT/assets/124405841/d07b314a-b324-4bf3-946f-298710d78bd9)

**Comment by charlieforward9** [comment]
Thats an error on my end, I had `do not store` toggled just to test things out during dev. This will be the next fix.

**Comment by charlieforward9** [comment]
Done.
