### ISSUE TITLE
[Analysis] normative comparison

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#161]
I’d like to be able to present text snippets that Physical Therapist you could use to help them complete their daily notes summaries. 

Even if we don’t have an LLM, could we include text snippets available for the therapist to cut and paste into their EMR?

***********

Normative comparison 

“Patients total time is 116/180 seconds, which is 43% of age-based norms, with a mean of 179.9 seconds.”

Interpretation:

“Patient displays deficits on Condition VisualPT/balance_model#5 and Condition VisualPT/balance_model#6 of the CTSIB which puts them at high risk (9x more likely) for a fall over the next 30 days. 

This test result demonstrates the medical necessity for physical therapy to reduce future falls risk”

--------------
Copied from VisualPT/visualPT#175 

text snippets: condition ratio information (these are exclusive; only include the worst ratio in the report)

“Patient demonstrates a 33.3% ratio on the vestibular function test which puts them in the dysfunctional category.”

“Patient demonstrates a 53.3% ratio on the visual dependence test which puts them in the dysfunctional category.”

“Patient demonstrates an 83.3% ratio on the somatic sensory function test which puts them in the dysfunctional category.”

---------------

![image](https://github.com/VisualPT/balance_model/assets/124405841/d5555109-b716-43a9-bc6c-7472d8745645)

**Comment by charlieforward9** [comment]
@Timothyrichpt could you send a modified version of the PDF with an idea of how that would be best conveyed within this document?

**Comment by charlieforward9** [comment]
@Timothyrichpt I am working on clearing all of these bugs/requests from the list. If this is still something you thing is necessary to go from 0 to 1, send a modified version of the PDF with the way the customer would expect it best.

**Comment by charlieforward9** [comment]
> “Patient displays deficits on Condition 5 and Condition 6 of the CTSIB which puts them at high risk (9x more likely) for a fall over the next 30 days.

Can I get a matrix of options to display here based on the conditions? 

What if they display a deficit on Condition 1-4? What exactly designates a deficit?

@Timothyrichpt

**Comment by Timothyrichpt** [comment]
[image0.jpeg]

So this is a great callout; the Physical Therapy literature is incomplete.

It is based on interferential statistics, using small sample sizes of subjects and trying to create a continuum of risk.

The fact is, the data just don’t exist.

Again, this represents an incredible opportunity for an improved testing tool the physical therapist can use to quickly and easily assess the risk in their patient population.


![imge](https://github.com/VisualPT/visualPT/assets/124405841/580e5bf2-5439-4548-85cb-7f34b7e0de80)



@charlieforward9

**Comment by charlieforward9** [comment]
Got it, we will hopefully be seeing this data in the PDF in the App Store release, with the completion of #174

**Comment by charlieforward9** [comment]
>  ![imge](https://github.com/VisualPT/visualPT/assets/124405841/580e5bf2-5439-4548-85cb-7f34b7e0de80)

**Comment by charlieforward9** [comment]
All the comparisons requested in the description of this issue are added into the PDF with https://github.com/VisualPT/visualPT/commit/abc2c39381026d7c90f3c10a757b909c9bfa52c7.

Subsequent near-term PDF improvements are related through #174



# Sample Report available from `v1.0.12` onwards.

![Sample Screenshot of CTSIB PDF Report](
https://github.com/VisualPT/visualPT/assets/62311337/a9784585-96dc-4d7e-ab33-51292f6ed3aa
)
