### ISSUE TITLE
[Sensor] Add Collection Angle to Metadata and Interface

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#163]
Not Urgent but Important:

Movement of the Tester/therapist can impact how the algorithm categorizes the subject.

In the first image, the subject is Stable, while in the second image, the subject is categorized as Sway. 

The subject did not move at all from image to image, only the tester/therapist moved.

![image](https://github.com/VisualPT/balance_model/assets/124405841/99c7445a-25dd-4800-984b-85d6259f5f62)

![image](https://github.com/VisualPT/balance_model/assets/124405841/b1bf2d76-76bb-4ce9-8569-384fb34ff62b)

@charlieforward9 
@DrBubbles42

**Comment by charlieforward9** [comment]
Closed by https://github.com/VisualPT/visualPT/pull/171
