### ISSUE TITLE
[Video] Ratio effect on different screen sizes

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#164]
![image](https://github.com/VisualPT/balance_model/assets/124405841/f7cdf516-d329-4ab2-976a-f358f94ad278)

**Comment by charlieforward9** [comment]
@Timothyrichpt Thanks for sharing this screenshot. This looks to be related to the fact that the original capture was on an ipad and then it is being validated on an iPhone with different screen dimensions. I will look into how to fix this...

**Comment by charlieforward9** [comment]
closed by #168
