### ISSUE TITLE
VPTGyro

### ISSUE THREAD

**Issue by charlieforward9** [charlieforward9/visualPT#167]
The therapist should always be taking the assessment with the phone upright. If there is any rotation to the phone, then an accurate classification cannot be guaranteed, thus, voiding the value and accuracy of the output, report and diagnosis. 

In order to address this issue, VisualPT can depend on the Gyroscope sensor to verify that the phone is in the correct orientation during the assessment.

Refer to these docs for implementing the sensor functionality: https://plus.fluttercommunity.dev/docs/sensors_plus/overview/

**Comment by Timothyrichpt** [comment]
What about a visual reference superimposed on the image? 

A bright, yellow vertical line would help the therapist hold the phone vertical as well as would improve the validation scoring.

**Comment by charlieforward9** [comment]
@Timothyrichpt For a quick workaround, I have outlined my plan in VisualPT/visualPT#110 .

**Comment by charlieforward9** [comment]
Closed by https://github.com/VisualPT/visualPT/pull/171
