### ISSUE TITLE
PDF does not email

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#188]
Most recent test at 2:55 PM on Friday, June 14 did not email to tim.richardson@fyzicalhq.com

![image](https://github.com/VisualPT/visualPT/assets/124405841/c4ec72f2-f8d2-49c3-a271-7acd50dbaecd)

@charlieforward9

**Comment by charlieforward9** [comment]
![image](https://github.com/VisualPT/visualPT/assets/62311337/31d10565-f2bb-4cb7-aafa-f0d014873432)

Worked for me. You sure you on the right email?

I'll redesign the email send modal to avoid users from aborting the operation on accident.
