### ISSUE TITLE
Display format on PDF 

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#189]
## Action Items

- [x] Display norm bars behind patient bars

<hr/>

Can we make the PDF display vertical bar graphs like the BodiTrak?

The VisualPT.ai will be easier to adopt if it gives therapists the same info (in the same format) they are currently used to getting.

Green an Red bars are Trails 1-3

Grey shadow background is Age & Gender matched normative values

![SOT-example BodiTrak score](https://github.com/VisualPT/visualPT/assets/124405841/07fb0aa7-8fa3-4f6a-b77b-4be9619846e9)

**Comment by charlieforward9** [comment]
To make age gender norms possible, I will need
- [x] Age ranges
- [X] Only two genders
- [x] Model holding these values (age_range, gender, equilibrium, score)
- [x] This database should update every time a new assessment verified by the PT.
- [x] The PT will have to verify assessment now
- [x] The PT should specify if they want the ANY/ALL data to be saved

This will be my next task.

**Comment by charlieforward9** [comment]
### Categories of age for use include:

* Children, age 6-12 years
* Adolescents, age 13-17 years
* Adults, age 18-64 years
* Older adults, age 65+.

[Ref](https://www.apta.org/patient-care/evidence-based-practice-resources/test-measures/clinical-test-of-sensory-interaction-and-balance-ctsib#:~:text=Categories%20of%20age,adults%2C%20age%2065%2B.)

![image](https://github.com/user-attachments/assets/e361d6c9-3fa8-44ba-86bf-6478feb8d71f)

To add more detail and customability to our database, I am creating these categories

``` graphql 
enum AgeRange {
  BABY # 0 to 5
  CHILD # 6 to 12
  ADOLESCENT # 13 to 17
  YOUNG_ADULT # 18 to 39
  MIDDLE_ADULT # 40 to 64
  OLDER_ADULT # 65 to 79
  ELDERLY # 80+
}
```

@Timothyrichpt Ask your peers if this is reasonable or if I should categorize it differently

**Comment by Timothyrichpt** [comment]
All of my CTSIB data is accurate with age, gender, etc. since August 24, 2024

![image](https://github.com/user-attachments/assets/2e1aff80-fb40-4a03-985c-4947f7ca8fa5)

**Comment by Timothyrichpt** [comment]
We will have data for these age cohorts:
YOUNG_ADULT # 18 to 39
  MIDDLE_ADULT # 40 to 64
  OLDER_ADULT # 65 to 79
  ELDERLY # 80+
@charlieforward9 
@DrBubbles42

**Comment by Timothyrichpt** [comment]
Here you go; 3rd tab 'Comparisons':
https://docs.google.com/spreadsheets/d/1nka_SQsqwzyHnzgefwxc4ic9ZmZDCrX-LuuS0vk4shI/edit?gid=1045616189#gid=1045616189

**Comment by Timothyrichpt** [comment]
![image](https://github.com/user-attachments/assets/a23040f1-c055-47e4-8606-60ccff628e96)

@charlieforward9 
@DrBubbles42

**Comment by Timothyrichpt** [comment]
Here is the graph:
![image](https://github.com/user-attachments/assets/15c5a01e-283d-45cc-a16e-ec67ed82836a)

@charlieforward9 
@DrBubbles42

**Comment by charlieforward9** [comment]
1d93b0e6c0ea24d2ab35530ea2d417f930dc398e adds 

```graphql
enum AgeRange {
  BABY_0_5
  CHILD_6_12
  TEEN_13_19
  ADULT_20_39
  ADULT_40_64
  SENIOR_65_69
  SENIOR_70_79
  SENIOR_80_84
  SENIOR_85_89
}
```

Tomorrows Tasks added to Issue description

**Comment by charlieforward9** [comment]
> ![image](https://github.com/user-attachments/assets/a23040f1-c055-47e4-8606-60ccff628e96)
> 

@Timothyrichpt where does this dataset come from? How many people were sampled per group? Another question, what is this gender?

**Comment by charlieforward9** [comment]
5cac96feaa91f80df18f7e5aeae16ce6474ffdf7
 adds norm chart to the PDF ![image](https://github.com/user-attachments/assets/0a8b2648-d087-43ed-84a0-ab8b64500d8c) 

Normative comparison text is still WIP.

Once completed, issue is considered closed, additional PDF development will continue in #186

**Comment by charlieforward9** [comment]
02f0bae2c9f9d23633d9aa1f2ec9dce3dcb2bb88 completes the normative comparison text.
