### ISSUE TITLE
Back button confuses typical users

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#201]
Oliver discovered of vulnerability in the UI; after Condition One he press the back button instead the bottom button.

Could we make the circle flash or pulse; drawing the eye to the bottom of the screen?

![image](https://github.com/user-attachments/assets/52e91c7b-df0a-4be3-969b-b24d452e3638)
@DrBubbles42 
@charlieforward9

**Comment by charlieforward9** [comment]
I will make the instructional modal larger and the background more tinted to resolve this.
