### ISSUE TITLE
Add 75% performance line on PDF

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#205]
To match the BodiTrak, we just need a thin, horizontal line at the 75th percentile drawn across all six conditions to indicate where the minimum threshold for upright human balance should be, irrespective of age or gender.

@charlieforward9 
@DrBubbles42

**Comment by charlieforward9** [comment]
![Reference BodiTrak Screenshot](https://private-user-images.githubusercontent.com/124405841/342550637-b0620e6f-f42b-4b05-a1de-4d73146725fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTc3NzEsIm5iZiI6MTcyNjExNzQ3MSwicGF0aCI6Ii8xMjQ0MDU4NDEvMzQyNTUwNjM3LWIwNjIwZTZmLWY0MmItNGIwNS1hMWRlLTRkNzMxNDY3MjVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwNTA0MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjI0MTQ5Y2ZkYjQ0ZDg0OWZlOTlmNmUxMDY0Mzg3NWFlNzI3N2VjMTRjZmFlMzA2NmVjMzliOGVlMDA1ZjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XT6A_mNNpV5a_007aJL2DxKTdbEuyckatGMWCx093Ow) 

I added axis dividers. Ill add that 75% line next.
