### ISSUE TITLE
Example of a Fall in condition six

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#206]
Jerry fell at 27 seconds.

The app is still waiting for the therapist to push the button; could we make this automatic so that once he breaks the frame of the bounding box the app shuts the test down and labels condition 6 a "fall"?

https://github.com/user-attachments/assets/79c057f4-d3cc-44af-b19b-b6104b82bc06

@charlieforward9 
@DrBubbles42

**Comment by charlieforward9** [comment]
As we discussed via phone call, we will be labeling the equilibrium score as 0 if there is a fall and ending the test early.

**Comment by charlieforward9** [comment]
Early fall detection is now built in 7cab54babcd6cd2b6534df87e522710e90f46dad

I will be adding a paused screen that will allow the user to restart the trial or continue to the next trial.

- [x] CapturePause (should include timer)
- [x] ~~TimerPause~~

**Comment by charlieforward9** [comment]
The trial is now "paused" when something notable happens and prompts the user to "reset" or "proceed" in fd74b3b5ce22ceeace82222f2ae465e87c8cec56
