### ISSUE TITLE
Measure Equilibrium Score

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#207]
@DrBubbles42 
@charlieforward9 
You guys should know how the Equilibrium Score is calculated:
[Link](https://vimeo.com/980847070/e43118ab57?share=copy)

**Comment by charlieforward9** [comment]
Part of equilibrium score involves the A/P sway. Conversation started [here](https://github.com/olexale/arkit_flutter_plugin/discussions/234)

**Comment by charlieforward9** [comment]
Our equilibrium score algorithm is located here

https://github.com/VisualPT/visualPT/blob/master/lib/features/assessment/config/ctsib/ctsib.dart#L246C3-L297C2
