### ISSUE TITLE
Calculation of the PT Prescription

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#213]
We need this to treat patients using the CTSIB test in the VisualPT.ai mobile app:

App doesn't work without this final piece.

Here is the step-by-step calculation of the PT Prescription:
https://docs.google.com/presentation/d/1nyToBoPw2sEPJ4Pe6lL4nJdlEUvp0KzpOKzzYpwhGnY/edit?usp=sharing

@DrBubbles42 
@charlieforward9

**Comment by charlieforward9** [comment]
02f0bae2c9f9d23633d9aa1f2ec9dce3dcb2bb88 should cover this up to the determination of stage exercise, which is reserved for when we strike a Fyzical deal.
