### ISSUE TITLE
Test discussion

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#39]
Hi Charlie!

**Comment by charlieforward9** [comment]
This is an Issue! Issues can be referenced with the hashtag (#). For example, see #40, the issue you just made.

Discussions are different. Issues are an area to resolve temporary issues related to the app, and eventually are "closed". Discussions are generally more longer-living, and serve as an area to talk about more significants topics, like the app architecture. 

With that said, I am closing the issue. Enjoy Github!
