### ISSUE TITLE
[Analysis] 'Reassessment' button doesn't work

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#40]
https://github.com/VisualPT/visualPT/assets/124405841/1d823790-64e5-465e-9e06-6c5cfae76464]()

**Comment by charlieforward9** [comment]
> [https://github.com/VisualPT/visualPT/assets/124405841/1d823790-64e5-465e-9e06-6c5cfae76464]()
 

That is a dead link! I know what you are talking about though, I will address this.

**Comment by Timothyrichpt** [comment]
I retested the reassessment button and it worked tonight on my iPhone
