### ISSUE TITLE
[Data] Label Camera Controls

### ISSUE THREAD

**Issue by charlieforward9** [charlieforward9/visualPT#45]
We need a dataset to train the pose classification model. In order to create this dataset, we are going to use the VisualPT application and its integrated data pipeline that goes through our backend for security, performance, and thorough data management.

**Comment by charlieforward9** [comment]
![image](https://github.com/VisualPT/visualPT/assets/62311337/eb2edc75-8ca3-4587-b8a7-d45afa2c3108)

Note the buttons at the bottom that will allow us to synchronously label image data while frames are available. 

This is still under development.

**Comment by charlieforward9** [comment]
Dataset should be appended to conditionally. We need to create a criteria for what qualifies as a valid datapoint. 

Criteria considerations
- Body is completely visible in frame (~80%+ landmark detection confidence)
- User has selected a label 
  - At Risk
  - No Risk

@DrBubbles42 any additional thoughts?

**Comment by DrBubbles42** [comment]
> Dataset should be appended to conditionally. We need to create a criteria for what qualifies as a valid datapoint.
> 
> Criteria considerations
> 
> * Body is completely visible in frame (~80%+ landmark detection confidence)
> * User has selected a label
>   
>   * At Risk
>   * No Risk
> 
> @DrBubbles42 any additional thoughts?

I think this looks good! do you have examples of what 80% confidence looks like? I also think it may be valuable to label some of the data ourselves to get started. It may take a while, but we can do something similar to what they did in that pose classification example you sent. If it is a failure move the image into the fail_images directory and if it is a success move it into the success_image directory. From here it would be easy to get labels because everything is sorted. It is also scalable for a multi class model which we can just split the fail_images into different classes. By images I mean the landmark wireframe. If Tim is unable to classify based on the image and the wireframe combined, then we discard that image from the training set. @charlieforward9

**Comment by charlieforward9** [comment]
> do you have examples of what 80% confidence looks like? 

I will need to access this from the inference output, will create a new task for this...

> we can do something similar to what they did in that pose classification example you sent. 

We can use that as a guide. Are you thinking about using a singular landmark detection as the classification input, a batch of them, or still considering options?

> If Tim is unable to classify based on the image and the wireframe combined, then we discard that image from the training set.

Elaborate on this please

**Comment by DrBubbles42** [comment]
Yes using one of the (33x5) landmark frames as input to the model.

To get a dataset rolling we will need to make sure that all of the images are correctly classified. If some are wrong it will produce a poor model. What I mean by this is that Tim should be able to classify the images with the landmark wire frame superimposed on the subject or by just the wireframe alone that tuple (33x5 datapoint) should not be used in training. 

What they did to count pushups was sort the up or down position into two different files and i think we should do the same instead of adding a dimension to the tuple for success or failure.

**Comment by charlieforward9** [comment]
To summarize (& make sure I understand):

1. Input: 1x 33x5 landmark frame

2. Must manually validate our labeled data -> 4 folders
   - Raw/Success/
   - Raw/Fail/
   - Verified/Success/
   - Verified/Fail/
 
All data will be stored in _Raw_ until we manually verify and confirm it's label, then it's sent to _Verified_.

Am I missing anything else regarding the pushup example?

**Comment by DrBubbles42** [comment]
yes this is correct we should aim to have about 100 in each Verified folder before I train the models.

**Comment by Timothyrichpt** [comment]
> > Dataset should be appended to conditionally. We need to create a criteria for what qualifies as a valid datapoint.
> > Criteria considerations
> > 
> > * Body is completely visible in frame (~80%+ landmark detection confidence)
> > * User has selected a label
> >   
> >   * At Risk
> >   * No Risk
> > 
> > @DrBubbles42 any additional thoughts?
> 
> I think this looks good! do you have examples of what 80% confidence looks like? I also think it may be valuable to label some of the data ourselves to get started. It may take a while, but we can do something similar to what they did in that pose classification example you sent. If it is a failure move the image into the fail_images directory and if it is a success move it into the success_image directory. From here it would be easy to get labels because everything is sorted. It is also scalable for a multi class model which we can just split the fail_images into different classes. By images I mean the landmark wireframe. If Tim is unable to classify based on the image and the wireframe combined, then we discard that image from the training set. @charlieforward9

*************************************************************
@charlieforward9 @DrBubbles42 @Timothyrichpt 
Not sure the 'At Risk' v. 'No Risk' is the appropriate language. 

From a Medico-legal standpoint, 'No Risk' is perilous. We can't label a patient or test result 'No Risk' on one day and have the patient fall down in the parking lot. 

'Low Risk' is more defensible.

I actually think we should seek to define movement - that's what the physical therapist does.
The PT would ask the patient to perform the test: Stand still with no trunk sway under 4 conditions:
1. Stable surface, eyes open
2. Stable surface, eyes closed
3. Unstable surface, eyes open
4. Unstable surface, eyes closed

The patient can fail the any of the 4 conditions and get a low score (test time/max time) in one of 3 Failure Motions:

1. Trunk flexes (sidebends) to maintain balance.
2. Legs step outside the Base of Support.
3. Arms windmill or abduct to maintain balance.

See the Failure Conditions for the CTSIB: https://docs.google.com/document/d/12xg0lQwGTeDL1MKKouTuwHUHwSxkiUoPY7iof2cYl-o/edit?usp=sharing

![Trunk flexion or Sidebending](https://github.com/VisualPT/visualPT/assets/124405841/59341d7a-524c-482a-afc8-dcebbcd6e4ff)

![Lower Extremity outside the Base of Support](https://github.com/VisualPT/visualPT/assets/124405841/b71cecf7-8f81-4c41-9479-b81f2a6fa404)

![Arm Abducted or Windmilling](https://github.com/VisualPT/visualPT/assets/124405841/6b724bf5-97f1-4514-85d7-c342593b419e)

**Comment by charlieforward9** [comment]
Here's what I got for controls. Trying to be as simple as possible: Tap to change class (with built in haptic feedback!). Any suggestions?

https://github.com/VisualPT/visualPT/assets/62311337/83bde75f-f79d-45d2-b9e0-ed1cf836157b

**Comment by charlieforward9** [comment]
Discussed UI with @Timothyrichpt 

Changing button names to:
- **FALL**
- **SAFE** (default)

**Comment by Timothyrichpt** [comment]
@charlieforward9 can I get more of those stick figure images as screenshots? I'd like to use them in my pitch PowerPoint's.

**Comment by charlieforward9** [comment]
Yes, I will be deploying the app soon and you can collect some samples from your own phone!

**Comment by Timothyrichpt** [comment]
Can I get that screenshot as an image?

**Comment by charlieforward9** [comment]
sample: 

https://github.com/VisualPT/visualPT/assets/62311337/849bc301-532a-4bd0-8619-27d6333f565d
