### ISSUE TITLE
[Data] Cloud-based containers

### ISSUE THREAD

**Issue by charlieforward9** [charlieforward9/visualPT#48]
Evaluate whether a Storage Service Class is necessary to implement or DataStore functionality suffices.

Considerations
* Will we want to access the raw image frames in the future?
* How do the costs of storing thousands of images per video compare with benefits of future analytics on these images?
* @Timothyrichpt Is it possible to build a HIPAA compliant UX to store non-anonymous images of patients for future labeling?

Containers
- Raw/Success
- Raw/Fail
- Verified/Success
- Verified/Fail

**Comment by Timothyrichpt** [comment]
@charlieforward9 
@DrBubbles42 
Can we get monthly cost estimate for the initial storage? perhaps the first 3 months or so while we are testing?

**Comment by charlieforward9** [comment]
I will create a simple cost diagram soon.

**Comment by charlieforward9** [comment]
I plan to use AWS Amplify to store the image in an S3 bucket and the landmarks in DynamoDB.

**data model**: _LabeledDetection_
- id : ID
- imgURL: string 
- landmarks : 33x5 Float[][]
   - still working on this
- classification : boolean
   - True: Static
   - False: Sway
   - (or is it more logical should it be the over way around???)

The image stored in the S3 will be named the id of the _LabeledDetection_. This creates an easy-to-match relationship between data model and file.
