### ISSUE TITLE
New build

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#61]
https://github.com/
VisualPT/visualPT/assets/124405841/ba3ee369-0f9f-42c7-be5e-27d28ec356ff

While using my iPhone, I'm not sure seeing the lines and the buttons also stopped working.

@charlieforward9

**Comment by charlieforward9** [comment]
@Timothyrichpt the model is designed to detect a FULL BODY. Showing only a leg cannot guarantee detection. I use this image to test:

https://datagen.tech/wp-content/uploads/2022/12/Pose-estimation_1.png.webp
