### ISSUE TITLE
The app sent seven emails for one test

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#64]
![image](https://github.com/VisualPT/visualPT/assets/124405841/ec872b60-d059-4a39-8ee6-f19dea1b0534)

**Comment by charlieforward9** [comment]
Let me know if this error persists.

**Comment by Timothyrichpt** [comment]
You were correct; that was my fat finger.


Love Your Life!

Tim


Want to schedule a call with Tim?

Put yourself on Tim's calendar here:

Calendly.com/Grow-With-Tim<https://calendly.com/grow-with-tim>


Tim Richardson, PT

Franchise Regional Consultant

Central Region, USA


FYZICAL LLC

World Headquarters

Bayou Professional Center

1751 Mound Street, <x-apple-data-detectors://2/1> Suite 101<x-apple-data-detectors://2/1>

Sarasota, Florida  34236<x-apple-data-detectors://2/1>


Mobile:  1.941.623.6109<tel:1.941.623.6109>


"Spelled Different Because We Are Different"


FYZICAL is Changing Lives and Changing Healthcare for Millions of Americans by Helping People Live Independently in Their Homes Without Fear of Falling.

On Aug 8, 2023, at 11:38 AM, Charles Richardson ***@***.***> wrote:

﻿

Let me know if this error persists.
