### ISSUE TITLE
[Auth] Can't login

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#76]
![image](https://github.com/VisualPT/visualPT/assets/124405841/0e07dd2f-b527-4188-90fe-09d79e5c93ea)

**Comment by Timothyrichpt** [comment]
This is the result when I put in an incorrect password, but there probably should be some sort of exception handling that tells me the password or the username is incorrect

**Comment by Timothyrichpt** [comment]
Same phenomenon, this one was on the iPad the first one was on the iPhone. Feels like there should be some sort of pop-up that says "incorrect password".


![image](https://github.com/VisualPT/visualPT/assets/124405841/bbd47220-f10c-4110-85ff-92243eac117c)

**Comment by Timothyrichpt** [comment]
It's actually not even letting me login with the correct password.

And, there's no back button so I have to delete the app and reinstall it in order to try again.

**Comment by charlieforward9** [comment]
Pending response: https://github.com/aws-amplify/amplify-flutter/issues/3583

**Comment by charlieforward9** [comment]
@Timothyrichpt working on a solution now. Narrowed down to a dependency or state issue. Until one is present, clear the app from your background instead of deleting it entirely for a reset.

**Comment by charlieforward9** [comment]
@Timothyrichpt working on a solution now. Narrowed down to a dependency or state issue. Until one is present, clear the app from your background instead of deleting it entirely for a reset.
