### ISSUE TITLE
[Assessment] Button stopped working in condition #1

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#78]
I was in low battery mode so the screen was shutting down and the red Stick Figure man appeared after the screen shut down the first time.

[https://github.com/VisualPT/visualPT/assets/124405841/c324faa6-30d1-4bdd-94ec-a1fb0ac1382e]()

**Comment by charlieforward9** [comment]
I believe this is related to the rendering performance. Related to #68 . This is a high priority ticket for me. More details in the [project](https://github.com/orgs/VisualPT/projects/2/views/1)
