### ISSUE TITLE
[Validation] Red bars do not show up on the iPad

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#79]
![image](https://github.com/VisualPT/visualPT/assets/124405841/41ee6aa1-0976-4c43-9a6e-653c6b7a17b3)

![image](https://github.com/VisualPT/visualPT/assets/124405841/e3384de1-c854-464f-acc9-65576e4716b7)

![image](https://github.com/VisualPT/visualPT/assets/124405841/eee28586-0709-4f07-972c-db3cde468f2e)

**Comment by charlieforward9** [comment]
This has been fixed somewhere along the way. 👍
