### ISSUE TITLE
[App] iPad Interface not displaying correctly

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#80]
![image](https://github.com/VisualPT/visualPT/assets/124405841/1a2937dc-52d6-4f43-ad04-9226feefaf39)

**Comment by Timothyrichpt** [comment]
https://github.com/VisualPT/visualPT/assets/124405841/5268b057-c1ec-4fc6-bb98-4f76eae5744e

**Comment by charlieforward9** [comment]
Duplicate of #62 

> I cannot hit the submit button when using the iPad. https://youtube.com/watch?v=WFbbXVxBxg4&feature=sharec Also, should there be lines or something to indicate that the ML/AI is measuring the angle?

**Comment by charlieforward9** [comment]
Detection indicator is present. Next release will have these changes.
