### ISSUE TITLE
I'm not sure the back button is working

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#95]
The back button doesn't obviously change frames when I try to go back and correct a "true/false" validation

https://github.com/VisualPT/visualPT/assets/124405841/39adad12-60fa-427e-a8f0-294fcb49c7a3

@charlieforward9

**Comment by charlieforward9** [comment]
Two things:

1) I expected **static** to have the patients arms crossed. Is that not a clinical requirement?

2) Since the (true/false) validation buttons move the files to different folders, it takes a little finesse to get it working, thanks for pointing this out. Fixing...
