### ISSUE TITLE
[Validation] Metadata: Assessment Condition Name

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#96]
If the name of the test condition(eg: condition#1, condition#2, condition#3, condition#4) was on the validation image. It would be easier to anticipate when the false condition is about to occur.
@charlieforward9

**Comment by charlieforward9** [comment]
The model we are training does not need to know what assessment is currently running, as it's sole purpose is to tell us whether a patient is **static** or **sway**. While this would not be a hard change to make, I am hesitant about its value to our progress.

**Comment by charlieforward9** [comment]
@DrBubbles42 Could this be useful for this model/next step in the future? I could add it to the metadata of the file you operate on.

**Comment by DrBubbles42** [comment]
> @DrBubbles42 Could this be useful for this model/next step in the future? I could add it to the metadata of the file you operate on.

Not for the binary model but for the multi class one yes

**Comment by charlieforward9** [comment]
Closed by https://github.com/VisualPT/visualPT/pull/171
